# Generated by Django 4.1.5 on 2023-01-30 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polished', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='polish',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
