# Generated by Django 4.1.5 on 2023-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polished', '0002_alter_brand_options_alter_polish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='polished.brand'),
        ),
        migrations.AlterField(
            model_name='review',
            name='polish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='polished.polish'),
        ),
    ]
